# Generated by Django 5.0.1 on 2024-01-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='accountNumber',
            field=models.BigIntegerField(),
        ),
    ]
