# Generated by Django 5.0.1 on 2024-01-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='accountId',
            field=models.CharField(max_length=36),
        ),
    ]
