# Generated by Django 5.0.1 on 2024-01-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_accountid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='accountId',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
