version: '3'

services:
  web:
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  celery:
    build:
      context: ./
    command: celery -A core worker -l info
    depends_on:
      - redis

  flower:
    build: 
      context: ./
    command: celery flower -A core --port=5555
    ports:
      - 5555:5555
    depends_on:
      - celery
