version: '3'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - 6379:6379

  celery:
    build: ./
    command: celery -A core worker -l info
    volumes:
      - ./:/app
    depends_on:
      - web
      - redis

  flower:
    build: ./
    command: celery -A core flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    depends_on:
      - web
      - celery
      - redis
