# Generated by Django 5.0.1 on 2024-01-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='companyId',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='companyName',
            field=models.CharField(max_length=64),
        ),
    ]
