# Generated by Django 5.0.1 on 2024-01-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companies_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='companyId',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
