# Generated by Django 5.0.1 on 2024-01-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='operationId',
            field=models.CharField(max_length=36),
        ),
    ]
