# Generated by Django 5.0.1 on 2024-01-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_operations_operationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='operationId',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
